[package]
name = "ts_to_html"
version = "0.1.0"
authors = ["stryku <stryku2393@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
regex = "1"
failure = "0.1.7"
exitfailure = "0.5.1"
